### ISSUE TITLE
请教学长一些关于Linux编译的问题

### ISSUE THREAD

**Issue by SeddonShen** [nju-mips/nemu-mips32#2]
您的仓库给了我很大的帮助，做为Linux的初学者，我没有弄清楚您nju-mips/minilab(run-linux分支)/M2/binary/下的vmlinux怎么编译出来的呢？

**Comment by SeddonShen** [comment]
我尝试通过nju-mips/linux下使用noop_defconfig进行重新编译，可是这样编译出来的vmlinux并不能在nemu中使用，会卡在最后：`Warning: unable to open an initial console.`并且这个产物的大小为3.96MB，而您编译出来的那个vmlinux只有3.60MB。因此我认为我找错了config文件。由于初学linux，还有很多没有了解的知识，特向您请教

**Comment by wierton** [comment]
非常抱歉，太久没来看这个项目，年久失修了，M2/binary的vmlinux是用的noop_legacy_boot_defconfig，noop_defconfig是用来与noop进行差分测试的

**Comment by SeddonShen** [comment]
谢谢学长啦，我们已经通过其他方法解决这个问题了，我们是来自西北工业大学的队伍，通过您的这个仓库配置了我们的差分测试框架，并成功修复了很多CPU内部的Bug。前人栽树，后人乘凉。感谢您和南京大学对我们带来的巨大帮助！
