### ISSUE TITLE
Why pa caculated from page_translate needs ioremap?

### ISSUE THREAD

**Issue by ipChrisLee** [nju-mips/nemu-mips32#3]
I'm learning mips by this perfect nemu-mips32. But I encounter a question when reading codes.

The function `prot_addr_with_attr` in `include/cpu/memory.h::62`, as I think, is a function that produces physical address (i.e. pa) from virtual address (i.e. va) and changes machine states (for example, there is exception raised). 

The question is, in my opinoin, `paddr=page_translate(addr, attr)` is the pa. But `prot_addr_with_attr` returns `ioremap(paddr)`, which is `paddr & 0x1FFFFFFF`. 

I wanna why here it needs `ioremap`. Since `PABITS` is 32 not 29, shouldn't we just use full 32 bits of `paddr`?

**Comment by wierton** [comment]
This project is from four or five years ago and is now almost no longer maintained. I can't confirm now whether this is a bug or not. If you have enough evidence and have test cases that can differentiate between the two behaviors, feel free to open a pull request.

**Comment by ipChrisLee** [comment]
> 

Thanks for your reply!
